### PR TITLE
Add Kubernetes Cluster Setup Scripts and Guide Using Kubeadm with Containerd

### PR DESCRIPTION
**Pull request by GMATHUR90**
This PR includes:

Scripts: Automates Kubernetes cluster setup with kubeadm and containerd.

**Common setup for all nodes**:
* Master node initialization and network plugin installation.
* Worker node join configuration.
* Documentation: Comprehensive guide (.md) detailing prerequisites, step-by-step instructions, and validation commands.

## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive guide for setting up a Kubernetes cluster using `kubeadm` with Containerd as the container runtime.
	- Added new scripts for automating the installation processes for master and worker nodes.
	- Included detailed instructions for cluster initialization, kubeconfig setup, network plugin installation, and node joining.

- **Bug Fixes**
	- Removed outdated Kubeadm Installation Guide to streamline documentation.

- **Documentation**
	- Updated and expanded installation documentation for Kubernetes using Containerd.
	- Added a new script for worker node setup, including pre-flight checks and joining commands.

### CODE REVIEW

**Comment by LondheShubham153** [comment]
> This PR includes:
> 
> Scripts: Automates Kubernetes cluster setup with kubeadm and containerd.
> 
> **Common setup for all nodes**:
> 
> * Master node initialization and network plugin installation.
> * Worker node join configuration.
> * Documentation: Comprehensive guide (.md) detailing prerequisites, step-by-step instructions, and validation commands.
> 
> ## Summary by CodeRabbit
> ## Release Notes
> * **New Features**
>   
>   * Introduced scripts for installing Kubernetes on master and worker nodes using Containerd.
>   * Added a comprehensive installation guide for Kubernetes setup with Containerd.
> * **Documentation**
>   
>   * Enhanced the Kubeadm Installation Guide with clearer instructions and structured steps.
>   * Updated the installation guide to include prerequisites and verification steps for cluster connectivity.
> * **Bug Fixes**
>   
>   * Improved clarity and organization in the installation documentation to facilitate easier setup.

thanks for the contribution.

can you create a directory `kubeadm/<files>`

**Comment by GMATHUR90** [comment]
Thanks for the prompt reply Shubham, i will do the same

**Comment by GMATHUR90** [comment]
Hi Shubham,
i have created kubeadm folder and moved all scripts into it. Please review PR and approve the same

**Review by LondheShubham153 — APPROVED** [review]

**Comment by GMATHUR90** [comment]
@LondheShubham153 Thanks for the approving PR.

**Pull request merged**
