### PR TITLE
Added and updated some commands. (small contribution)

### PR DESCRIPTION
**Pull request by Dark-Kernel**
updated commands to their standard forms.

### CODE REVIEW

**Review by paragpallavsingh — COMMENTED** [review]
updates are good.
do we need to setup user and group as we did for docker

**Comment by Dark-Kernel** [comment]
> updates are good. do we need to setup user and group as we did for docker

Nope, now it contains everything you need to set up.

**Comment by LondheShubham153** [comment]
> > updates are good. do we need to setup user and group as we did for docker
> 
> Nope, now it contains everything you need in setup.

awaiting review @paragpallavsingh @Dark-Kernel

**Comment by paragpallavsingh** [comment]
image

verified

**Comment by Dark-Kernel** [comment]
Cool!

**Pull request merged**
